env: local
port: 3006
db:
  port: 4007
  host: 127.0.0.1
  password:
  user: root
  name: users
broker:
  rabbit:
    addr: amqp://guest:guest@localhost:5672/
    topics:
      email: email_notification
