repomock:
	mockgen -source internal/db/repository.go -destination internal/db/mocks/repo_mock.go -package repomock

storagemock:
	mockgen -source internal/storage/images.go -destination internal/storage/mocks/images_mock.go -package storagemock