env: local
port: 3005

broker:
  addr: localhost:9092
  metrics:
    topics:
      decreaseActiveRentsAmount: ACTIVE_CAR_RENTS_INC
      increaseActiveRentsAmount: ACTIVE_CAR_RENTS_DEC
      increaseRentsCancel: RENTS_CANCELED
      notifyBrandDemand: REQUESTED_BRANDS

db:
  host: localhost
  user: postgres
  password: 1787
  name: postgres
  port: 4005