env: local
port: 3005


broker:
  addr: amqp://rabbitmq:1787@localhost:6672
  topics:
    metrics:
      responseTime: CARSHARING_RESPONSE_TIME
      notifyBrandDemand: REQUESTED_BRANDS

db:
  host: localhost
  user: postgres
  password: 1787
  name: cars
  port: 4005


cache:
  addr: 0.0.0.0:4006
  password: ""

services:
  payment:
    apiKey: sk_test_51OU56CDOnc0MdcTNBwddO2cn8NrEebjfuAGjBjj9xSyKmiUO4ajJ1vZ0yBoOsAMq0HjHqCmis2niwoj2EZYCDLOA00lcCUlWxh
  user: localhost:3006