// Code generated by MockGen. DO NOT EDIT.
// Source: internal/notifications/notifier.go

// Package notmock is a generated GoMock package.
package notmock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockNotifier) Login(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockNotifierMockRecorder) Login(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockNotifier)(nil).Login), email)
}

// Registration mocks base method.
func (m *MockNotifier) Registration(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Registration", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Registration indicates an expected call of Registration.
func (mr *MockNotifierMockRecorder) Registration(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Registration", reflect.TypeOf((*MockNotifier)(nil).Registration), email)
}
