repomock:
	mockgen -source internal/db/repository.go -destination internal/db/mocks/repo_mock.go -package repomock

notifmock:
	mockgen -source internal/notifications/notifier.go -destination internal/notifications/mocks/notifier_mock.go -package notifier_mock